# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: option_profile.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'option_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14option_profile.proto\x12\x0eoption_profile\"\xaa\x02\n\rOptionProfile\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x0c\n\x04spot\x18\x03 \x01(\r\x12\x14\n\x07min_dte\x18\x04 \x01(\x11H\x00\x88\x01\x01\x12\x18\n\x0bsec_min_dte\x18\x05 \x01(\x11H\x01\x88\x01\x01\x12\x18\n\x10major_call_gamma\x18\x06 \x01(\r\x12\x17\n\x0fmajor_put_gamma\x18\x07 \x01(\r\x12\x18\n\x10major_long_gamma\x18\x08 \x01(\r\x12\x19\n\x11major_short_gamma\x18\t \x01(\r\x12\x34\n\x0emini_contracts\x18\n \x03(\x0b\x32\x1c.option_profile.MiniContractB\n\n\x08_min_dteB\x0e\n\x0c_sec_min_dte\"\xfc\x01\n\x0cMiniContract\x12\x0e\n\x06strike\x18\x01 \x01(\r\x12\x11\n\tcall_ivol\x18\x02 \x01(\r\x12\x10\n\x08put_ivol\x18\x03 \x01(\r\x12\x14\n\x0c\x63\x61ll_cvolume\x18\x04 \x01(\x11\x12\x1b\n\x13\x63\x61ll_cvolume_priors\x18\x05 \x03(\x11\x12\x18\n\x0bput_cvolume\x18\x06 \x01(\x11H\x00\x88\x01\x01\x12\x43\n\x12put_cvolume_priors\x18\x07 \x01(\x0b\x32\".option_profile.MiniContractPriorsH\x01\x88\x01\x01\x42\x0e\n\x0c_put_cvolumeB\x15\n\x13_put_cvolume_priors\"$\n\x12MiniContractPriors\x12\x0e\n\x06values\x18\x01 \x03(\x11\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'option_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTIONPROFILE']._serialized_start=41
  _globals['_OPTIONPROFILE']._serialized_end=339
  _globals['_MINICONTRACT']._serialized_start=342
  _globals['_MINICONTRACT']._serialized_end=594
  _globals['_MINICONTRACTPRIORS']._serialized_start=596
  _globals['_MINICONTRACTPRIORS']._serialized_end=632
# @@protoc_insertion_point(module_scope)
